version: '3.8'

services:
  zookeeper:
    hostname: zookeeper
    image: zookeeper:3.9.1
    ports:
      - "2181:2181"
  clickhouse-server:
    image: clickhouse/clickhouse-server:24.1.5.6
    hostname: clickhouse-server
    volumes:
      - ./config.xml:/etc/clickhouse-server/config.xml
    depends_on:
      - zookeeper
      - prometheus
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    ports:
      - "8123:8123"
      - "9363:9363"
    healthcheck:
      test: [ "CMD", "bash", "-c", "cat < /dev/null > /dev/tcp/127.0.0.1/8123" ]
      interval: 5s
      timeout: 60s
      retries: 120
  prometheus:
    image: bitnami/prometheus:latest
    hostname: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/opt/bitnami/prometheus/conf/prometheus.yml