version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.12.9-management
    container_name: rabbitmq_3.12.9
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=123456
