version: '3.8'
services:
  oap:
    image: apache/skywalking-oap-server:9.2.0
    ports:
      - "12800:12800"
      - "11800:11800"
  ui:
    image: apache/skywalking-ui:9.2.0
    ports:
      - "8080:8080"
    environment:
      - SW_OAP_ADDRESS=http://oap:12800
