version: '3.8'
services:
  broker1:
    image: wurstmeister/kafka
    hostname: broker1
    container_name: broker1
    ports:
      - "9091:9091"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: broker1
      KAFKA_ADVERTISED_PORT: 9091
      KAFKA_HOST_NAME: broker1
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2181,zoo3:2181
      KAFKA_LISTENERS: PLAINTEXT://broker1:9091
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker1:9091
      JMX_PORT: 9988
    volumes:
      - ./kafka1/data:/var/lib/kafka/data
    external_links:
      - zoo1
      - zoo2
      - zoo3
    networks:
      default:
        ipv4_address: 172.69.0.91

  broker2:
    image: wurstmeister/kafka
    hostname: broker2
    container_name: broker2
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ADVERTISED_HOST_NAME: broker2
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_HOST_NAME: broker2
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2181,zoo3:2181
      KAFKA_LISTENERS: PLAINTEXT://broker2:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker2:9092
      JMX_PORT: 9988
    volumes:
      - ./kafka2/data:/var/lib/kafka/data
    external_links:
      - zoo1
      - zoo2
      - zoo3
    networks:
      default:
        ipv4_address: 172.69.0.92

  broker3:
    image: wurstmeister/kafka
    hostname: broker3
    container_name: broker3
    ports:
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ADVERTISED_HOST_NAME: broker3
      KAFKA_ADVERTISED_PORT: 9093
      KAFKA_HOST_NAME: broker3
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2181,zoo3:2181
      KAFKA_LISTENERS: PLAINTEXT://broker3:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker3:9093
      JMX_PORT: 9988
    volumes:
      - ./kafka3/data:/var/lib/kafka/data
    external_links:
      - zoo1
      - zoo2
      - zoo3
    networks:
      default:
        ipv4_address: 172.69.0.93

networks:
  default:
    external:
      name: ka-zk